apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: APP_NAME
  name: APP_NAME
  namespace: NAMESPACE
spec:
  replicas: 2
  selector:
    matchLabels:
      app: APP_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - image: IMAGE_TAG
        imagePullPolicy: Always
        name: APP_NAME
        volumeMounts:
        - name: tls-volume
          readOnly: true
          mountPath: "/etc/tls"
      volumes:
      - name: tls-volume
        secret:
          secretName: APP_NAME-tls
